title: Alan Shortis
version: 0.1
email: alan@short.is
description: "Alan Shortis is a web developer, occasional designer and music nerd based in Nottingham."
baseurl: ""
url: "http://short.is"
image: "https://test.short.is/img/as-og.png"
incremental: true
permalink: /:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
include:
  - .htaccess
  - fonts
  - img
  - favicon.ico
  - _pages
exclude:
  - _src
  - README.md
  - package.json
  - yarn.lock
  - node_modules
  - gulpfile.js
keep_files:
  - css
  - js
collections:
  listening:
    output: true
    permalink: /:path
