title: Alan Shortis
version: 1.2.0
email: alan@short.is
description: "Alan Shortis is a web developer, occasional designer and music nerd based in Nottingham."
baseurl: ""
url: "http://short.is"
image: "https://short.is/img/as-og.png"
incremental: true
permalink: /:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    disable: true
include:
  - .htaccess
  - fonts
  - img
  - favicon.ico
  - favicon-152.png
  - _pages
exclude:
  - _src
  - README.md
  - package*
  - yarn.lock
  - node_modules
  - gulpfile.js
keep_files:
  - css
  - js
